GET http://localhost:3001/api/product 

###
GET http://localhost:3001/api/product/6284c0fd3ad1995085fd395a
###

GET http://localhost:3001/api/category/penis

###

POST http://localhost:3001/api/product
Content-Type: application/json

{
"image": "www.google.com/chair2",
  "title": "Chair2",
  "description": "This a chair2",
  "price": 292,
  "stock": 1,
  "category": ["furniture"]
}

###

PUT http://localhost:3001/api/product/6284c0fd3ad1995085fd395a
Content-Type: application/json

{

}

###

DELETE http://localhost:3001/api/product/12121