GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/6284aac5db2b2b7070c6f885

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
  "firstname": "admin",
  "lastname": "admin",
  "password": "admin",
  "email": "admin"
}

###

POST http://localhost:3000/api/login 
Content-Type: application/json

{
  "email": "admin",
  "password": "admin"
}

###

###

DELETE http://localhost:3000/api/logout



###

DELETE http://localhost:3000/api/user/1234