GET http://localhost:3000/api/order

###

POST http://localhost:3000/api/order
Content-Type: application/json

{
  "customer": "6283598560765e36787c6867",
  "products": ["Produkt 1", "Produkt 2"]
}

###

PUT http://localhost:3000/api/order/6283515af3f6ab16ccf62710
Content-Type: application/json

{
  
}

###

DELETE http://localhost:3000/api/order/1234