GET http://localhost:3000/api/order

###

GET http://localhost:3000/api/order/6284c1933ad1995085fd395e

###

POST http://localhost:3000/api/order
Content-Type: application/json

{
 
  "products": ["Produkt 1", "Produkt 2"],
  "paymentMethod": "swish",
  "total": 299,
  "deliveryMethod": "schenker",
  "isOrderSent": false,
   "address": {
    "street": "Åkannavägen",
    "zipcode": 43540,
    "city": "Mölnlycke"
  }
  
}

###

PUT http://localhost:3000/api/order/6284eca183735855607db609
Content-Type: application/json

{
  
}

###

DELETE http://localhost:3000/api/order/1234